name: netana
version: '3.1.18'
summary: Electronic Network Analyzer
description: |
  This pro    environment:
      PATH: ${SNAP}/usr/bin:${PATH}
      PYTHONPATH: ${SNAP}/usr/lib/python3.6gram solves electronic AC & DC Mash and Node network
  equations using matrix algebra.

base: core20
grade: devel
confinement: devmode

apps:
  netana:
#    environment:
#      PATH: ${SNAP}/usr/bin:${PATH}
#      PYTHONPATH: ${SNAP}/usr/lib/python3.8
  command: bin/main.py
  plugs: [home]

parts:
  netana:
    plugin: python  # python3 is default for core20
    source: .
    source-subdir: netana
    stage-packages:
       - python3-tk
       - python3-matplotlib
       - python3-numpy
    plugin: dump
    organize:
      "*.py" : bin/

    

