name: netana
version: '3.1.18'
summary: Electronic Network Analyzer
description: |
  This program solves electronic AC & DC Mash and Node network
  equations using matrix algebra.

base: core20
grade: devel
confinement: devmode

apps:
  netana:
   command: bin/main.py
   plugs: [home]

parts:
  netana:
    plugin: python3
    source: .
    source-subdir: netana 
    plugin: dump
    organize:
      "*" : bin/

    stage-packages:
      - python3
      - python3-tk
      - python3-matplotlib
      - python3-numpy
    

